# Generated by Django 4.2.2 on 2023-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.CharField(default='#0a0a0a', max_length=10),
        ),
    ]
