# Generated by Django 4.2.2 on 2023-06-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_company_background_color_alter_company_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='card_border',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_box_shadow',
            field=models.CharField(default='1px 1px 10px 0px rgb(20,20,20, .2)', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_button_background_color',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_button_background_color_hover',
            field=models.CharField(default='royalblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_button_color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
