# Generated by Django 4.2.2 on 2023-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_company_card_border_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='card_label_color',
            field=models.CharField(blank=True, default='#333333', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_line_background_color',
            field=models.CharField(blank=True, default='#202020', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_text_border_bottom',
            field=models.CharField(blank=True, default='2px solid black', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_text_color',
            field=models.CharField(blank=True, default='#202020', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_title_font_color',
            field=models.CharField(blank=True, default='#202020', max_length=40),
        ),
    ]
