# Generated by Django 4.2.2 on 2023-06-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_company_card_label_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='card_icon_color',
            field=models.CharField(blank=True, default='#202020', max_length=20),
        ),
    ]
