# Generated by Django 4.2.2 on 2023-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_company_card_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link_on_video',
            field=models.TextField(blank=True),
        ),
    ]
